[workspace]
resolver = "2"
members = [
    "flexpad",
    "flexpad-grid"
]

[workspace.package]
version = "0.0.2"
authors = ["Dave Wathen <dave@wathenweb.com>"]
rust-version = "1.65"
edition = "2021"
